# Generated by Django 3.2.25 on 2024-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rata', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'For Star'), (5, 'Five Star'), (6, 'Six Star'), (7, 'Seven Star'), (8, 'Eight Star'), (9, 'Nine Star'), (10, 'Ten Star')])),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
